### ISSUE TITLE
How to control the frame rate?

### ISSUE THREAD

**Issue by anishg-cn** [liqvidjs/liqvid#18]
Is there a way to change the frame rate in react?

**Comment by ysulyma** [comment]
If you mean for rendering to static video, see https://liqvidjs.org/docs/rp-master/render/#fps, and relatedly https://liqvidjs.org/docs/rp-master/thumbs/#frequency for generating thumbnails

If you mean the in-browser view: there's no concept of "frames" or "frame rate" in Liqvid. Everything happens with `requestAnimationFrame`, so the view will be updated as frequently as the browser is able to

**Comment by anishg-cn** [comment]
@ysulyma I meant the in-browser view

**Comment by ysulyma** [comment]
Ok then yeah there's no such thing as frame rate per se. Are you running into a performance issue?

**Comment by anishg-cn** [comment]
@ysulyma yes, the video is not smooth there is a lot of lagging, is there a way to improve the performance?

**Comment by ysulyma** [comment]
That's likely an issue with your code then. Can you provide a sample?
