### ISSUE TITLE
When developing and run npm start what is the URL to see the result?

### ISSUE THREAD

**Issue by GilbertMizrahi** [liqvidjs/liqvid#20]
I expected to get some info like: go to localhost:3000 or something like that, but I didn't.

So, at what port I can see the result?

**Comment by ysulyma** [comment]
http://localhost:8000

It's supposed to open automatically, but I guess it doesn't always. I'll add a console.log!

**Comment by GilbertMizrahi** [comment]
Great. Thanks.
