### ISSUE TITLE
[feature request] Add function to import mp4 as background video.

### ISSUE THREAD

**Issue by cocoonkid** [liqvidjs/liqvid#24]
[feature request] Add function to import mp4 as background video.

That way this could be used to (background) embed youtube/video.
It would be very helpful to add additional information to or add clickable links to resources etc.

Thank you for your consideration.

**Comment by ysulyma** [comment]
This is what [`<Video>`](https://liqvidjs.org/docs/reference/Video/) is for—is that not working for you?

**Comment by cocoonkid** [comment]
Will do thanks haha :-)
