### ISSUE TITLE
new Script() not working with number duration

### ISSUE THREAD

**Issue by anishg-cn** [liqvidjs/liqvid#26]
when calling `new Script(markers)` with the markers having durations as number instead of string, it is throwing error.

I think in the following code the `parseTime` function should check if the duration is of type number or string before operating on the duration.

```    for (const marker of markers) {
      if (marker.length === 2) {
        const [, duration] = marker;
        marker[1] = time;
        marker[2] = time + parseTime(duration);
      } else {
        const [, begin, end] = marker;
        marker[1] = parseTime(begin);
        marker[2] = parseTime(end);
      }

      time = marker[2];
    }
```
    
 The error is following:
 
 ```liqvid.mjs:887 
        
       Uncaught (in promise) TypeError: str.split is not a function
    at parseTime (liqvid.mjs:887:1)
    at new Script (liqvid.mjs:3251:1)
```
    

@ysulyma please check.

**Comment by ysulyma** [comment]
@anishg-cn this is actually the current intended behavior, the types in the constructor are wrong. But agree that you should be able to pass numeric durations to Script. I'm feeling pretty ill today, I can cut new versions tomorrow. For now pass durations as strings.

**Comment by anishg-cn** [comment]
@ysulyma ok thanks

**Comment by ysulyma** [comment]
@anishg-cn try with v2.1.5
