### ISSUE TITLE
Keymap should not throw error when unbinding a thing that is no longer bound

### ISSUE THREAD

**Issue by ysulyma** [liqvidjs/liqvid#33]
since other code could delete the bindings to override keyboard controls.

**Comment by anishg-cn** [comment]
@ysulyma is this bug related to the following error? If yes, then can you please tell the status of it?

![image](https://user-images.githubusercontent.com/83653579/209650766-e49a67bc-76c5-47d4-ae0d-12816c1b4456.png)

**Comment by ysulyma** [comment]
@anishg-cn upgrade to latest version, this was fixed in `liqvid@2.1.9` / `@liqvid/keymap@1.1.4`

**Comment by anishg-cn** [comment]
@ysulyma ok thanks
